name: Devocionalico - Versículos

on:
  schedule:
    # 07:00 - horário de Brasília
    - cron: "0 10 * * *"

    # 12:00 - horário de Brasília
    - cron: "0 15 * * *"

    # 19:00 - horário de Brasília
    - cron: "0 22 * * *"

  workflow_dispatch:

jobs:
  enviar-versiculo:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Executar Devocionalico
        run: python bot.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
