name: Devocionalico - Versículos

on:
  schedule:
    - cron: "0 10 * * *"
    - cron: "0 15 * * *"
    - cron: "0 22 * * *"

  workflow_dispatch:

jobs:
  enviar-versiculo:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Baixar o código
        uses: actions/checkout@v4

      - name: 🐍 Verificar Python
        run: python --version

      - name: 🤖 Executar Devocionalico
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MEMBER_ROLE_ID: ${{ secrets.MEMBER_ROLE_ID }}
        run: python bot.py
